image: "python:3.10"

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

.before_script_template:
  before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry install

test:
  extends: .before_script_template
  stage: test
  script:
    - poetry run pytest
  only:
    - merge_requests
    - main
    - tags

deploy_test:
  extends: .before_script_template
  stage: deploy
  script:
    - poetry config repositories.testpypi https://test.pypi.org/legacy/
    - poetry build
    - poetry publish --repository=testpypi --username=$PYPI_API_TOKEN_USERNAME --password=$PYPI_API_TOKEN_PASSWORD
  only:
    - tags
  when: manual

deploy_prod:
  extends: .before_script_template
  stage: deploy
  script:
    - poetry build
    - poetry publish --username=$PYPI_API_TOKEN_USERNAME --password=$PYPI_API_TOKEN_PASSWORD
  only:
    - tags
